# Generated by Django 3.2.6 on 2021-08-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=123, null=True)),
                ('email', models.CharField(blank=True, max_length=123, null=True)),
            ],
        ),
    ]
