# Generated by Django 3.2.6 on 2021-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_emailverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverify',
            name='token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
