# Generated by Django 3.2.6 on 2021-08-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_emailverify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='token',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
