# Generated by Django 3.2.6 on 2021-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_emailverify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='email',
            field=models.CharField(blank=True, max_length=123, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverify',
            name='username',
            field=models.CharField(blank=True, max_length=123, null=True, unique=True),
        ),
    ]
